### ISSUE TITLE
change projects

### ISSUE THREAD

**Issue by ananya** [ananya/opencode#5]

**Comment by ananya** [comment]
https://github.com/opencode18/dataviz-gallery

https://github.com/opencode18/ProDesigner

https://github.com/opencode18/OpenCode-Collaborative
https://github.com/betterclever/ZapTap
https://github.com/himanshub16/ProxyMan
https://github.com/Anna-Assistant/Anna
https://github.com/himanshub16/cool-physics
https://github.com/gostudent/Algorithms
https://opencodeiiita.github.io/CodeFemme/

**Comment by sggts04** [comment]
Done
